### ISSUE TITLE
Disable modules in ci integration script

### ISSUE THREAD

**Issue by kjk** [fuzzitdev/example-go#4]
`go-fuzz` doesn't support modules (see https://github.com/dvyukov/go-fuzz/issues/195) so we should add:
```
export GO111MODULE="off"
```
at the top of `fuzzit.sh` (like I had to do in https://github.com/gomarkdown/markdown/commit/f70ab624d0d8f8512b11f0f19a69e4d44be63130).

Otherwise, things will break for packages that use modules.

I can make a PR.

**Comment by yevgenypats** [comment]
Doesn't go-fuzz already set GO11MODULE="off"? if not then please open a PR as you suggested.

**Comment by yevgenypats** [comment]
Closing as this was merged.
